# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    # Files stored in `docs` directory
    directory: '/docs'
    ignore:
      # Needs to be exactly version 3
      - dependency-name: 'remark-math'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    # Files stored in `scikitjs-browser` directory
    directory: '/scikitjs-browser'
    ignore:
      # Needs to be exactly version 0.3.3
      - dependency-name: 'danfojs*'
      # Needs to be exactly version 3.11.0
      - dependency-name: '@tensorflow/tfjs*'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    # Files stored in `scikitjs-node` directory
    directory: '/scikitjs-node'
    schedule:
      interval: 'daily'
      ignore:
        # Needs to be exactly version 0.3.3
        - dependency-name: 'danfojs-node*'
        # Needs to be exactly version 3.11.0
        - dependency-name: '@tensorflow/tfjs-node*'
