[build]
  publish = "docs/build"
  command = "npm install && npm run build:docs"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"